import os
import argparse
import json
import torch
import cv2
import yaml
import numpy as np
from pathlib import Path
from tqdm import tqdm
from PIL import Image as PILImage

# SAM3 Imports
from sam3.model_builder import build_sam3_image_model
from sam3.train.data.sam3_image_dataset import Datapoint, Image as SAMImage, FindQueryLoaded, InferenceMetadata
from sam3.train.data.collator import collate_fn_api
from sam3.model.utils.misc import copy_data_to_device
from sam3.train.transforms.basic_for_api import ComposeAPI, RandomResizeAPI, ToTensorAPI, NormalizeAPI
from lora_layers import LoRAConfig, apply_lora_to_model, load_lora_weights
from torchvision.ops import nms

def create_coco_skeleton():
    return {
        "info": {"description": "Auto-generated by SAM3 inference"},
        "categories": [{"id": 1, "name": "leaf"}],
        "images": [],
        "annotations": []
    }

def mask_to_coco_annotations(mask_tensor, img_id, start_ann_id, orig_w, orig_h, min_area=50):
    mask_resized = torch.nn.functional.interpolate(
        mask_tensor.unsqueeze(0).unsqueeze(0).float(), 
        size=(orig_h, orig_w), 
        mode='bilinear', 
        align_corners=False
    ).squeeze() > 0.5
    
    mask_np = mask_resized.cpu().numpy().astype(np.uint8)
    contours, _ = cv2.findContours(mask_np, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    annotations = []
    current_ann_id = start_ann_id
    
    for c in contours:
        if len(c) >= 3:
            area = int(cv2.contourArea(c))
            if area > min_area:
                x, y, w, h = cv2.boundingRect(c)
                annotations.append({
                    "id": current_ann_id,
                    "image_id": img_id,
                    "category_id": 1,
                    "bbox": [float(x), float(y), float(w), float(h)],
                    "area": area,
                    "segmentation": [c.flatten().tolist()],
                    "iscrowd": 0
                })
                current_ann_id += 1
                
    return annotations, current_ann_id

def run_inference_and_save_coco(model, image_paths, text_prompt, output_json_path, device, resolution=1008, prob_threshold=0.3, min_area=50):
    transform = ComposeAPI([
        RandomResizeAPI(sizes=[resolution], max_size=resolution, square=True, consistent_transform=False),
        ToTensorAPI(),
        NormalizeAPI(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    
    coco_data = create_coco_skeleton()
    img_id_counter = 1
    ann_id_counter = 1
    
    model.eval()
    with torch.no_grad():
        for img_path in tqdm(image_paths, desc=f"Inference ({Path(output_json_path).name})"):
            pil_img = PILImage.open(img_path).convert("RGB")
            orig_w, orig_h = pil_img.size
            
            coco_data["images"].append({
                "id": img_id_counter,
                "file_name": Path(img_path).name,
                "width": orig_w,
                "height": orig_h
            })
            
            sam_image = SAMImage(data=pil_img, objects=[], size=[orig_h, orig_w])
            query = FindQueryLoaded(
                query_text=text_prompt,
                image_id=0,
                object_ids_output=[],
                is_exhaustive=True,
                query_processing_order=0,
                inference_metadata=InferenceMetadata(
                    coco_image_id=0, original_image_id=0, original_category_id=1,
                    original_size=[orig_w, orig_h], object_id=0, frame_index=0,
                )
            )
            
            dp = transform(Datapoint(images=[sam_image], find_queries=[query]))
            batch = collate_fn_api([dp], dict_key="input", with_seg_masks=False)["input"]
            batch = copy_data_to_device(batch, device)
            
            outputs = model(batch)
            last_output = outputs[-1]

            pred_logits = last_output['pred_logits']
            pred_boxes = last_output['pred_boxes']
            pred_masks = last_output.get('pred_masks', None)

            if pred_masks is not None:
                out_probs = pred_logits.sigmoid()
                scores = out_probs[0, :, :].max(dim=-1)[0]
                keep_idx = scores > prob_threshold

                if keep_idx.any():
                    valid_masks = pred_masks[0, keep_idx].sigmoid()
                    valid_scores = scores[keep_idx]
                    
                    boxes_cxcywh = pred_boxes[0, keep_idx]
                    cx, cy, w, h = boxes_cxcywh.unbind(-1)
                    x1, y1 = (cx - w / 2) * orig_w, (cy - h / 2) * orig_h
                    x2, y2 = (cx + w / 2) * orig_w, (cy + h / 2) * orig_h
                    boxes_xyxy = torch.stack([x1, y1, x2, y2], dim=-1)

                    nms_keep = nms(boxes_xyxy, valid_scores, iou_threshold=0.5)
                    for mask in valid_masks[nms_keep]:
                        anns, ann_id_counter = mask_to_coco_annotations(
                            mask, img_id_counter, ann_id_counter, orig_w, orig_h, min_area=min_area
                        )
                        coco_data["annotations"].extend(anns)
                    
            img_id_counter += 1

    output_path = Path(output_json_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(coco_data, f)
    print(f"[OK] Found {len(coco_data['annotations'])} objects.")

def main():
    parser = argparse.ArgumentParser(description="SAM3 Inference with dynamic config")
    parser.add_argument("--config", type=str, required=True, help="Path to custom_config.yaml")
    parser.add_argument("--image-dir", type=str, required=True, help="Folder with images")
    parser.add_argument("--prompt", type=str, required=True, help="Text prompt")
    parser.add_argument("--weights", type=str, default=None, help="Path to .pt (if not specified then take from config)")
    parser.add_argument("--out-dir", type=str, default="results_json", help="JSON folder")
    parser.add_argument("--threshold", type=float, default=0.3, help="Confidence threshold")
    args = parser.parse_args()

    # 1. Read config
    with open(args.config, 'r') as f:
        cfg = yaml.safe_load(f)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"🔧 Settings are loaded from {args.config}")
    
    # Читаем значение из конфига (по умолчанию 200, если не задано)
    config_min_area = cfg.get('inference', {}).get('min_area', 200)
    
    image_paths = [os.path.join(args.image_dir, f) for f in os.listdir(args.image_dir) 
                   if Path(f).suffix.lower() in {'.jpg', '.jpeg', '.png'}]

    # 2. Base model from config
    model_name = cfg.get('model', {}).get('name', 'facebook/sam3')
    print(f"📦 Base model assembly: {model_name}...")
    model = build_sam3_image_model(
        device=device.type, 
        compile=False, 
        load_from_HF=True, 
        bpe_path="sam3/assets/bpe_simple_vocab_16e6.txt.gz", 
        eval_mode=True
    )
    model.to(device)

    base_json = os.path.join(args.out_dir, "base_annotations.coco.json")
    run_inference_and_save_coco(model, image_paths, args.prompt, base_json, device, prob_threshold=args.threshold, min_area=config_min_area)

    # 3. LoRA preparation from config
    print("\n🔗 Applying LoRA...")
    l_cfg = cfg['lora']
    lora_config = LoRAConfig(
        rank=l_cfg['rank'],
        alpha=l_cfg['alpha'],
        dropout=l_cfg.get('dropout', 0.1),
        target_modules=l_cfg['target_modules'], 
        apply_to_vision_encoder=l_cfg.get('apply_to_vision_encoder', False),
        apply_to_text_encoder=l_cfg.get('apply_to_text_encoder', False),
        apply_to_geometry_encoder=l_cfg.get('apply_to_geometry_encoder', False),
        apply_to_detr_encoder=l_cfg.get('apply_to_detr_encoder', False),
        apply_to_detr_decoder=l_cfg.get('apply_to_detr_decoder', True),
        apply_to_mask_decoder=l_cfg.get('apply_to_mask_decoder', True)
    )
    apply_lora_to_model(model, lora_config)

    # Weights path: --weights, otherwise take from config
    w_path = args.weights
    if not w_path:
        out_root = cfg.get('output', {}).get('output_dir', 'outputs/leaves_lora')
        w_path = os.path.join(out_root, "best_lora_weights.pt")
    
    print(f"💾 Weights are loading: {w_path}")
    load_lora_weights(model, w_path)
    model.to(device)

    # 4. Lora inference
    lora_json = os.path.join(args.out_dir, "lora_annotations.coco.json")
    run_inference_and_save_coco(model, image_paths, args.prompt, lora_json, device, prob_threshold=args.threshold, min_area=config_min_area)
    
    print("\n🚀 All files are saved in folder:", args.out_dir)

if __name__ == "__main__":
    main()